committees = [
    ("hsag00", "Agriculture"),
    ("hsap00", "Appropriations"),
    ("hsas00", "Armed Services"),
    ("hsbu00", "Budget"),
    ("hsed00", "Education and the Workforce"),
    ("hsif00", "Energy and Commerce"),
    ("hsso00", "Ethics"),
    ("hsba00", "Financial Services"),
    ("hsfa00", "Foreign Affairs"),
    ("hshm00", "Homeland Security"),
    ("hsha00", "House Administration"),
    ("hsju00", "Judiciary"),
    ("hsii00", "Natural Resources"),
    ("hsgo00", "Oversight and Government Reform"),
    ("hsru00", "Rules"),
    ("hssy00", "Science, Space, and Technology"),
    ("hssm00", "Small Business"),
    ("hspw00", "Transportation and Infrastructure"),
    ("hsvr00", "Veterans' Affairs"),
    ("hswm00", "Ways and Means"),
    ("hlig00", "Permanent Select Committee on Intelligence"),
    ("hlzi00", "Select Committee on the Events Surrounding the 2012 Terrorist Attack in Benghazi"),
    ("ssaf00", "Agriculture, Nutrition, and Forestry"),
    ("ssap00", "Appropriations"),
    ("ssas00", "Armed Services"),
    ("ssbk00", "Banking, Housing, and Urban Affairs"),
    ("ssbu00", "Budget"),
    ("sscm00", "Commerce, Science, and Transportation"),
    ("sseg00", "Energy and Natural Resources"),
    ("ssev00", "Environment and Public Works"),
    ("ssfi00", "Finance"),
    ("ssfr00", "Foreign Relations"),
    ("sshr00", "Health, Education, Labor, and Pensions"),
    ("ssga00", "Homeland Security and Governmental Affairs"),
    ("ssju00", "Judiciary"),
    ("ssra00", "Rules and Administration"),
    ("sssb00", "Small Business and Entrepreneurship"),
    ("ssva00", "Veterans' Affairs"),
    ("spag00", "Aging"),
    ("slet00", "Ethics"),
    ("slia00", "Indian Affairs"),
    ("slin00", "Intelligence"),
    ("jsec00", "Joint Economic"),
    ("jslc00", "Joint Library"),
    ("jspr00", "Joint Printing"),
    ("jstx00", "Joint Taxation"),
]
